# Generated by Django 3.2.5 on 2021-07-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_area_crimeincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='number_of_crimes',
            field=models.IntegerField(default=0),
        ),
    ]
