# Generated by Django 3.2.5 on 2021-07-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_area_number_of_crimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='incident',
        ),
    ]
