# Generated by Django 3.2.5 on 2021-08-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_crimeincident_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimeincident',
            name='report_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='crimeincident',
            name='report_status',
            field=models.CharField(max_length=20),
        ),
    ]
