# Generated by Django 3.2.5 on 2021-08-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210819_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=200)),
                ('post_id', models.IntegerField()),
            ],
        ),
    ]
